const API_URL = "http://127.0.0.1:8000";

async function handleUpload() {
  const fileInput = document.getElementById("pdfFile");
  const status = document.getElementById("uploadStatus");
  const btn = document.getElementById("uploadBtn");

  if (!fileInput.files[0]) return alert("Please select a PDF file first.");

  const formData = new FormData();
  formData.append("file", fileInput.files[0]);

  status.innerText = "Processing pipeline active...";
  status.style.color = "#6366f1";
  btn.disabled = true;

  try {
    const response = await fetch(`${API_URL}/upload-pdf`, {
      method: "POST",
      body: formData,
    });
    const result = await response.json();

    if (result.status === "success") {
      status.style.color = "#059669";
      status.innerHTML = `${result.message} <span class="collection-tag">📚 Collection: ${result.collection}</span>`;
    } else {
      status.style.color = "#dc2626";
      status.innerText = result.message;
    }
  } catch (error) {
    status.style.color = "#dc2626";
    status.innerText =
      "Pipeline execution failed. Is the FastAPI server running?";
  } finally {
    btn.disabled = false;
  }
}

async function handleChat() {
  const query = document.getElementById("chatQuery").value.trim();
  const results = document.getElementById("chat-results");
  const status = document.getElementById("chatStatus");

  if (!query) return;

  const formData = new FormData();
  formData.append("question", query);

  status.style.color = "#6366f1";
  status.innerText = "Retrieving context...";

  try {
    const response = await fetch(`${API_URL}/chat`, {
      method: "POST",
      body: formData,
    });
    const result = await response.json();

    if (result.status === "success") {
      const pagesHtml =
        result.pages && result.pages.length > 0
          ? `<div class="page-ref-box">
             <span class="page-ref-label">&#128196; Referenced Pages</span>
             ${result.pages.map((p) => `<span class="page-badge">Page ${p}</span>`).join("")}
           </div>`
          : "";

      results.innerHTML += `
        <p><strong>Q:</strong> ${query}</p>
        <p><strong>A:</strong> ${result.answer}</p>
        ${pagesHtml}
        <hr>`;
      results.scrollTop = results.scrollHeight;
      document.getElementById("chatQuery").value = "";
    } else {
      status.style.color = "#dc2626";
      status.innerText = result.answer;
      return;
    }
  } catch (error) {
    status.style.color = "#dc2626";
    status.innerText = "Query retrieval failed. Is the FastAPI server running?";
  } finally {
    status.innerText = "";
  }
}

async function handleQuiz() {
  const topic = document.getElementById("quizTopic").value.trim();
  const results = document.getElementById("quiz-results");
  const status = document.getElementById("quizStatus");

  if (!topic) return;

  const formData = new FormData();
  formData.append("topic", topic);

  status.style.color = "#6366f1";
  status.innerText = "Generating structured assessment...";
  results.innerHTML = "";

  try {
    const response = await fetch(`${API_URL}/generate-quiz`, {
      method: "POST",
      body: formData,
    });
    const data = await response.json();

    if (data.status !== "success") {
      status.style.color = "#dc2626";
      status.innerText = data.message || "Generation failed.";
      return;
    }

    const quiz = data.quiz;
    let html = `<h3>Assessment: ${topic}</h3>`;

    // --- MCQs ---
    if (quiz.mcqs && quiz.mcqs.length > 0) {
      html += `<h4>Multiple Choice</h4>`;
      quiz.mcqs.forEach((item, i) => {
        html += `
          <div class="mcq-item">
            <strong>Q${i + 1}: ${item.question}</strong><br>
            ${item.options.map((opt) => `• ${opt}<br>`).join("")}
            <small style="color: #059669">✓ Correct: ${item.correct_answer}</small>
          </div>`;
      });
    }

    // FIX: short_answers were generated by backend but never rendered
    if (quiz.short_answers && quiz.short_answers.length > 0) {
      html += `<h4>Short Answer Questions</h4>`;
      quiz.short_answers.forEach((q, i) => {
        html += `
          <div class="mcq-item">
            <strong>SA${i + 1}: ${q}</strong>
          </div>`;
      });
    }

    results.innerHTML = html;
    status.innerText = "";
  } catch (error) {
    status.style.color = "#dc2626";
    status.innerText = "Generation failed. Is the FastAPI server running?";
  }
}

// Allow pressing Enter to submit chat query
document.addEventListener("DOMContentLoaded", () => {
  document.getElementById("chatQuery").addEventListener("keydown", (e) => {
    if (e.key === "Enter") handleChat();
  });
  document.getElementById("quizTopic").addEventListener("keydown", (e) => {
    if (e.key === "Enter") handleQuiz();
  });
});
